nelmio_cors:
    defaults:
        allow_origin: []
        allow_headers: []
        allow_methods: []
        forced_allow_origin_value: ~
    paths:
        '^/':
            allow_origin: ['%env(CORS_AUTHORIZATION)%']
            allow_headers: ['Origin', 'Content-Type', 'Authorization']
            allow_methods: ['OPTIONS', 'POST', 'GET', 'PUT', 'DELETE']