nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['Origin', 'Content-Type', 'Authorization']
        allow_methods: ['OPTIONS', 'POST', 'GET', 'PUT', 'DELETE']
        forced_allow_origin_value: ~